### ISSUE TITLE
How to change the security protocol to SASL_PLAINTEXT?

### ISSUE THREAD

**Issue by talk2vijyant** [BrightTag/kafkameter#28]
While sending the message on Kafka, I want to update the 
security.protocol=SASL_PLAINTEXT
sasl.mechanism=SCRAM-SHA-512
sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username="admin" password="admin";

Can you please help, its urgent to me.

**Comment by gus** [comment]
Morning, @talk2vijyant-

Somehow I have become sole admin and member on this repo though I have never touched it and I haven't worked at Signal (fka BrightTag) for quite a while now. To make a long story short, unless some previous owners of this repo want to provide support -- such as @codyaray (hi, Cody ;) -- it's going to be safer to assume this repo is defunct and no further support will be provided.

That said, you can definitely fork this repo or take a look at [some of the forks](https://github.com/BrightTag/kafkameter/network/members) to see if maybe anyone else is continuing the work.

Cheers,
Gus

**Comment by codyaray** [comment]
Hey @gus ! It's been a long time, man. When're we gonna work together again? :)

Yeah, I recently lost all access to this repo and all things BrightTag, so there's nothing I can do here anyway. Not that I have much time anyway...

Speaking of Kafka, I'm actually at Confluent now.... so I'll ask and see if anyone wants to take this project over there. Definitely no promises.

@talk2vijyant As Gus said, since its urgent and this repo is unsupported, its probably easiest to fork it and add it yourself or see if another fork has added this feature. Sorry :(

**Comment by talk2vijyant** [comment]
No problem.  Thank you for your response @gus and @codyaray . I have got an alternative for now.

**Comment by gus** [comment]
@codyaray made you an Admin in case Confluent (or anyone) is interested
