### ISSUE TITLE
How to send specific message or message set per user/thread with Synthetic Load Generator?

### ISSUE THREAD

**Issue by daluu** [BrightTag/kafkameter#4]
Hi,

I'm not really knowledgeable with the internals of JMeter (haven't looked into the developer-specific documentation yet), and I skimmed through your readme about the Synthetic Load Generator and Synthetic Load Description and can't quite wrap my head around it yet (for other varying use cases), will have to try it out to figure things out.

But here's what I want to do, maybe you might have ideas to help me out. In my use case scenario, I can have N users in the system. Each user will have some activity and such activity translates as messages produced into kafka. Each user may perform similar but different activity, take for example hiking - we have a group of hikers, each one hiking a different trail. Each point/section of a trail is a message, the whole trail is a set of messages that follow a sequence (in the data in the message). Different hiking users will send different messages while they hike, but there could be sort of duplicates as in hiker A & B taking same trail but hiker C a different one.

The message format itself can be a very long verbose JSON structure, and as I need to send a "set" of messages in sequence (1, 2...N) per user, the weighted distribution technique may not be suitable (I can't figure out how to apply that here).

Rather my thoughts are to use pre-captured messages that I replay back (with some dynamic modification at runtime like timestamps for example and other unique identifiers) as part of load generation. I use this same technique for functional testing right now.

In JMeter usage & terminology, a JMeter thread is a user of the system under test. And so in my test scenario with the Synthetic Load Generator, I want to track and determine what message group to send by keying off (say) the thread ID of the thread that is executing the producer sampler & Load Generator Config Element. I might use an internal hash/map to track the thread ID to a particular message set stored in the filesystem. Multiple threads may use same message set, but that type of collision should only occur as you scale up the # of threads where # threads greater than # of message sets available.

How might you suggest I go about this in actual implementation of the Synthetic Load Generator? Does the Synthetic Load Generator class (and it's derived subclasses) have the ability to get/set JMeter variables and properties like you can from Beanshell, etc.?

**Comment by codyaray** [comment]
The easiest way to understand the testing setup is to break it into two pieces:
1. the piece which generates your message for sending to Kafka
2. the piece which actually sends the message to Kafka

This project provides (2) and a framework for building (1). The bit about the "Synthetic Load Description" was only an example (albeit one from our own usage). You can use (2) without (1). You mentioned replaying actual data; that's actually far simpler than trying to generate realistic data. You can just use a CSV Data Set or similar source in JMeter to read in real data instead of building on the framework from (1). 

Opening the [Sample JMeter Test Plan](https://github.com/BrightTag/kafkameter/blob/master/Tagserve-Kafka.jmx) may really help you understand how (1) and (2) are wired together (using some common JMeter components as well).

If you need to modify the data in any way (you mentioned timestamps), then there may be something built into JMeter to help, but I don't remember anything off the top of my head. If nothing else, a small custom solution may do.

In the simplest case, you just implement the tiny `SyntheticLoadGenerator` interface. The `#nextMessage()` method is called once per iteration. The response string is sent to Kafka. For example, the following will send the same string message to Kafka every time.

    import co.signal.loadgen.SyntheticLoadGenerator;

    public class DummyGenerator implements SyntheticLoadGenerator {
      public DummyGenerator(String ignored) {}

      @Override
      public String nextMessage() {
        return "Hey! Dum-dum! You give me gum-gum.";
      }
    }

This already supports passing in a config (which is `ignored` above). This could be the replay data itself. Then you could just store a counter/index of where you are in the replay, read the next line on every call of `#nextMessage()`, and update the timestamp in the replayed message before returning it.

Hope this helps!

**Comment by daluu** [comment]
Thanks for the advice, working on creating my own message generator. 

Got some questions for you, do you have any tips for how I can:

* get and set JMeter variables (already defined in test plan) within the Java class for the custom message generator? I tried basing on some code you had under co/signal/loadgen/LoadGenerator.java. But I'm getting null value returned from a get. Maybe I misconfigured something in the code, or that's not the right way to do it. Wanted to check with you on it.

* log status or debug info (or exception messages) to JMeter's log from the Java custom message class? Right now I dump some stuff to stdout for the time being.

**Comment by daluu** [comment]
Well I figured out the JMeter variables part following a link from your blog post for this project. Still want to figure out how to log to JMeter though.

**Comment by daluu** [comment]
Well, figured out the JMeter logging too. Had to use this class with getLoggerForClass()

https://jmeter.apache.org/api/org/apache/jorphan/logging/LoggingManager.html

which had dependency on jorphan-2.6.jar (had to find it online) and JMeter/lib/logkit-2.0.jar

**Comment by codyaray** [comment]
Glad you figured it all out! Feel free to share more details here for anyone else stumbling on it. Marking as closed.

-Cody

**Comment by sonaliverma44** [comment]
> Well I figured out the JMeter variables part following a link from your blog post for this project. Still want to figure out how to log to JMeter though.

Can you please share the link here. kafkameter is substituting the value for the variables using  get/set properties for me in the messages.

**Comment by codyaray** [comment]
I assume they're references http://codyaray.com/2014/07/custom-jmeter-samplers-and-config-elements since that's linked from this homepage: https://github.com/BrightTag/kafkameter
