### ISSUE TITLE
Statistics Information about kafkameter load generation?

### ISSUE THREAD

**Issue by daluu** [BrightTag/kafkameter#7]
More of a discussion topic and request here.

I don't think this project currently mentions any statistics or information regardling kafka load generation with JMeter so far. In your blog post:

http://codyaray.com/2014/07/custom-jmeter-samplers-and-config-elements

you mention: "for my use case, I wanted a simple way to load test a system which reads its requests from Kafka. This has two requirements: read or generate synthetic requests (messages), publish the messages to a Kafka topic"

Kafka is a relatively new technology, and as far as I recall any mentions about load/performance testing come to articles like these:

https://engineering.linkedin.com/kafka/benchmarking-apache-kafka-2-million-writes-second-three-cheap-machines

https://grey-boundary.io/load-testing-apache-kafka-on-aws/

which seem to be more of benchmarking or generic stressing of a kafka environment without much regard for custom messages and other requirements specific to an organization. Your tool helps satisfy the need for the customizations needed for load testing a kafka-based environment.

It would be nice to know of some stats regarding usage of this tool (as a point of reference) such as what amount of load has been generated by this plugin like:

* number of kafka messages sent per second
* kafka message sizes (in bytes) used in the load
* number of producers or JMeter threads generating the load
* load generation schemes (ramp up/down ratio/times, whether used with things like JMeter plugin throughput shaping timer, etc.)
* how much load generated by kafkameter on some given setup (single box hardware, JMeter distributed setup) before JMeter/kafkameter crapped out from lack of resources OR the generated load was good enough for you to not need to scale further
* how much load generated against the system under test by kafkameter

Other users of kafkameter (if there are any so far) could also chime in on this topic. I would provide my input once I've used kafkameter for some load testing. For now, I'm still working on the customizations needed before I can send the payload over to kafka in our system.

@codyaray, if you can/want to provide stats input, it could also be a new post to your blog :)

**Comment by codyaray** [comment]
@daluu Sorry for the radio silence here, I actually just switched jobs and am no longer actively using this tool. Not to mention we hadn't needed to use this tool at the previous company for quite a while either. All this to say, here are some answers from memory. YMMV. :)

We were sending messages between 1k and 10k bytes. Not huge by any means. It really depends on how you configure your max message size in Kafka and your consumer clients though. We were using 50 JMeter threads/users to generate the load. We didn't really bother with any ramp up/down times since we were sending to a queue; we assumed the queue could handle the traffic but our downstream services might fail. We were generating several million messages over the period of a few minutes but we didn't time it any more specifically than that. (Our testing was focused on a stats aggregation and storage system; since we aggregated into 30s buckets, it didn't really matter to us.)

-Cody
